
services:
  db:
    image: postgres:14.10-alpine
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
    volumes:
      - db-volume:/var/lib/postgresql
  adminer:
    image: adminer
    ports:
      - 6970:8080
  api:
    build: .
    depends_on:
      - db
    ports:
      - 5050:80
volumes:
  db-volume: